[phases.setup]
nixPkgs = [
  "(python311.withPackages (ps: with ps; [ flask gunicorn ]))"
]

[phases.install]
# Optional: Add this if you still want to run any script
cmds = []

[phases.start]
cmd = "gunicorn main:app"
