[phases.setup]
nixPkgs = ["python311", "git"]

[phases.install]
cmds = [
  "pip install --break-system-packages --upgrade pip",
  "pip install --break-system-packages -r requirements.txt"
]

[phases.start]
cmd = "gunicorn main:app"
