[phases.setup]
nixPkgs = [
  "(python311.withPackages (ps: with ps; [ flask gunicorn pypdf2 python-dotenv langchain googletrans youtube-transcript-api sentence-transformers langchain-groq faiss-cpu]))"
]

[phases.install]
# Optional: Add this if you still want to run any script
cmds = []

[phases.start]
cmd = "gunicorn main:app"
