apiVersion: apps/v1
kind: Deployment
metadata:
  name: superllm-backend
  labels:
    app: superllm-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superllm-backend
  template:
    metadata:
      labels:
        app: superllm-backend
    spec:
      containers:
      - name: flask-container
        image: docker.io/lokesh9307/superllm-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: superllm-service
spec:
  selector:
    app: superllm-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
